### ISSUE TITLE
无法导入微信账单文件

### ISSUE THREAD

**Issue by kklod** [chryoung/beancount_importer#1]
![image](https://user-images.githubusercontent.com/50442661/134639690-d52a3d08-9f91-4204-8821-a222020b445c.png)

**Comment by chryoung** [comment]
你好kklod，看起来是https://github.com/chryoung/beancount_importer/blob/master/importer/wechat.py 的第32行代码抛出的异常。
![image](https://user-images.githubusercontent.com/29620734/134838485-c7b5c60f-26fc-4988-a4c8-82e7f71db848.png)
请你检查一下微信账单csv是否有一行的第六列是“出”这个字符呢？如果是的话，请问它是在第几行，属于交易记录的一部分吗？

**Comment by kklod** [comment]
![image](https://user-images.githubusercontent.com/50442661/134896811-1224aabb-1777-461d-8627-ef1c98b5dc62.png)
  已标记，不少

**Comment by chryoung** [comment]
看起来是栏位错位了一格，原本应该读取金额（表格中F列）变成了读取收支（表格中E列）。
程序需要删除第一个字符￥以获得数字部分，而“支出”去掉第一个字符后为“出”，从而引起异常。
你可以先尝试再A列前面增加一列看看程序是否能够正常工作，同时我也新增了一个[分支](https://github.com/chryoung/beancount_importer/tree/logging)加入了日志和异常处理，应该能帮助定位该问题。

**Comment by kklod** [comment]
> 看起来是栏位错位了一格，原本应该读取金额（表格中F列）变成了读取收支（表格中E列）。 程序需要删除第一个字符￥以获得数字部分，而“支出”去掉第一个字符后为“出”，从而引起异常。 你可以先尝试再A列前面增加一列看看程序是否能够正常工作，同时我也新增了一个[分支](https://github.com/chryoung/beancount_importer/tree/logging)加入了日志和异常处理，应该能帮助定位该问题。

尝试增加A行前增加一列，报错日期栏数据格式不对......我下载了最新的branch，能够正常导入微信csv，问题解决！ 谢谢。
